# Multiple Linear Regression

### Importing Libraries

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

### Loading Data

In [32]:
# Importing data from csv files
data = pd.read_csv("https://docs.google.com/spreadsheets/d/1PVUH65sonHSI-g7JSdLlTzpXdtkAx77gJ0NfVCQcq6A/export?gid=547974534&format=csv")
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [33]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

### Creating Multiple Regression model

In [34]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [35]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [36]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [37]:
reg.intercept_

0.29603261264909486

In [8]:
reg.score(x,y)

0.4066811952814283

#### Formula for adj. R-squared

$R^2_{adj.} = 1 - (1 - R^2)*\frac{n-1}{n-p-1}$

In [9]:
x.shape

(84, 2)

In [10]:
r2_adj = 1 - (1-reg.score(x,y)) * ((x.shape[0]-1)/(x.shape[0]-x.shape[1]-1))

In [11]:
r2_adj

0.3920313482513401

## Feature Selection

In [12]:
from sklearn.feature_selection import f_regression

In [13]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [14]:
p_value = f_regression(x,y)[1]

In [15]:
p_value.round(3)

array([0.   , 0.676])

## Feature Scaling(Standardization)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(x)

StandardScaler()

In [19]:
x_scaled = scaler.transform(x)

In [20]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

### Regression with Scaled input

In [21]:
model = LinearRegression()
model.fit(x_scaled, y)

LinearRegression()

In [22]:
model.score(x_scaled, y)

0.4066811952814283

In [23]:
model.coef_

array([ 0.17181389, -0.00703007])

In [24]:
model.intercept_

3.330238095238095

In [25]:
reg_summary = pd.DataFrame([['Bias'], ['SAT'], ['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = model.intercept_, model.coef_[0], model.coef_[1]

In [26]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

### Making Prediction with standardization coeff (weight)

In [27]:
new_data = pd.DataFrame([[1700, 2], [1800, 3]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           3

In [28]:
model.predict(new_data)
## This unusual pattern happens because of model is trained on standardized inputs
## now we will standardize the inputs with the exact scaler vaues

/home/alexender/Desktop/Projects/My_Projects/envs/Data_Science/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 312.57415484])

In [29]:
new_scaled = scaler.transform(new_data)
new_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643,  1.10632974]])

In [30]:
model.predict(new_scaled)

array([3.09051403, 3.24759839])