# Matrix Operation

### Import Libraries

In [1]:
import numpy as np

### Addition

In [2]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Difference

In [5]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Addition and Difference of Vector 

In [6]:
m3 = np.array([1, 2, 3, 4, 5])
m4 = np.array([5, 4, 3, 2, 1])

In [7]:
m3+m4

array([6, 6, 6, 6, 6])

In [8]:
m3-m4

array([-4, -2,  0,  2,  4])