# Matrix Operation

### Import Libraries

In [1]:
import numpy as np

### Addition

In [2]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Difference

In [5]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Addition and Difference of Vector 

In [6]:
m3 = np.array([1, 2, 3, 4, 5])
m4 = np.array([5, 4, 3, 2, 1])

In [7]:
m3+m4

array([6, 6, 6, 6, 6])

In [8]:
m3-m4

array([-4, -2,  0,  2,  4])

### Transpose of a Matrix

In [12]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

### Dot Product

### Vector*Vector

In [18]:
x = np.array([5, 12, 6])
y = np.array([-3, 0, 17])

In [19]:
np.dot(x, y)

87

### Scalar * Scalar

In [20]:
np.dot(5, 6)

30

In [21]:
np.dot(15, 16)

240

### Scalar * Vector

In [22]:
np.dot(5, x)

array([25, 60, 30])

### Scalar * Matrix

In [23]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [24]:
np.dot(5, A)

array([[ 25,  60,  30],
       [-15,   0,  70]])

### Matrix * Matrix

In [25]:
B = np.array([[2, -1], [8, 0], [3, 14]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3, 14]])

In [26]:
np.dot(A, B)

array([[124,  79],
       [ 36, 199]])