# Import Libraries

In [11]:
import numpy as np

### Scalar

In [12]:
s = 5

In [13]:
s

5

### Vector

In [14]:
vec = np.array([5, 2, 1])

In [15]:
vec

array([5, 2, 1])

### Matrices

In [16]:
mat = np.array([[5, 12, 6], [-3, 0, 14]])

In [17]:
mat

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [18]:
type(s)

int

In [19]:
type(vec)

numpy.ndarray

In [20]:
type(mat)

numpy.ndarray

In [26]:
s_array = np.array(s)
type(s_array)

numpy.ndarray

### Data Shapes

In [27]:
mat.shape

(2, 3)

In [28]:
vec.shape

(3,)

In [29]:
s_array.shape

()

### Creating a column vector

In [30]:
vec.reshape(1, 3)

array([[5, 2, 1]])

In [31]:
vec.reshape(3, 1)

array([[5],
       [2],
       [1]])