# Absenteeism Use Case 

### Preprocessing the Data 

### Importing the library and Datasets

In [1]:
import pandas as pd 

raw_data_csv = pd.read_csv("https://docs.google.com/spreadsheets/d/1NmK8V0b-ZTI8ulMcMjEWmV3Tduzaow3Ec7TahfDcUHY/export?gid=788161934&format=csv")
raw_data_csv.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [2]:
raw_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [3]:
df = raw_data_csv.copy()
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

### Dropping the Unique ID

In [4]:
df.drop(['ID'], axis=1, inplace=True)

In [5]:
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### 'Reason for Absence'

In [6]:
df['Reason for Absence'].min(), df['Reason for Absence'].max()

(0, 28)

In [7]:
# pd.unique(df['Reason for Absence'])
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [8]:
len(df['Reason for Absence'].unique())

28

In [9]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

### get_dummies()

In [10]:
reason_for_absence = pd.get_dummies(df['Reason for Absence'], dtype='int64', drop_first=True)

In [11]:
reason_for_absence

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 27 columns]

In [12]:
reason_for_absence['check'] = reason_for_absence.sum(axis=1)
reason_for_absence

1  2  3  4  5  6  7  8  9  10  ...  19  21  22  23  24  25  26  27  28  \
0    0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   1   0   0   
1    0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   0   0   0   
2    0  0  0  0  0  0  0  0  0   0  ...   0   0   0   1   0   0   0   0   0   
3    0  0  0  0  0  0  1  0  0   0  ...   0   0   0   0   0   0   0   0   0   
4    0  0  0  0  0  0  0  0  0   0  ...   0   0   0   1   0   0   0   0   0   
..  .. .. .. .. .. .. .. .. ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
695  0  0  0  0  0  0  0  0  0   1  ...   0   0   0   0   0   0   0   0   0   
696  0  0  0  0  0  1  0  0  0   0  ...   0   0   0   0   0   0   0   0   0   
697  0  0  0  0  0  0  0  0  0   1  ...   0   0   0   0   0   0   0   0   0   
698  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   1   0   0   0   0   0   
699  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   0   0   1   

     check  
0        1  
1        0  
2        1  
3        1  
4        1  
..     ...  
695      1  
696      1  
697      1  
698      1  
699      1  

[700 rows x 28 columns]

In [13]:
reason_for_absence['check'].sum()

662

In [14]:
reason_for_absence['check'].unique()

array([1, 0])

In [15]:
reason_for_absence.drop(['check'], axis=1, inplace=True)
reason_for_absence

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 27 columns]

### Group Reason for Absence

In [16]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [17]:
reason_for_absence.columns.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       21, 22, 23, 24, 25, 26, 27, 28], dtype=object)

In [18]:
df.drop(['Reason for Absence'], axis=1, inplace=True) 

In [19]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [20]:
reason_for_absence.loc[: , 1:14]

1  2  3  4  5  6  7  8  9  10  11  12  13  14
0    0  0  0  0  0  0  0  0  0   0   0   0   0   0
1    0  0  0  0  0  0  0  0  0   0   0   0   0   0
2    0  0  0  0  0  0  0  0  0   0   0   0   0   0
3    0  0  0  0  0  0  1  0  0   0   0   0   0   0
4    0  0  0  0  0  0  0  0  0   0   0   0   0   0
..  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..
695  0  0  0  0  0  0  0  0  0   1   0   0   0   0
696  0  0  0  0  0  1  0  0  0   0   0   0   0   0
697  0  0  0  0  0  0  0  0  0   1   0   0   0   0
698  0  0  0  0  0  0  0  0  0   0   0   0   0   0
699  0  0  0  0  0  0  0  0  0   0   0   0   0   0

[700 rows x 14 columns]

In [21]:
reason_1 = reason_for_absence.loc[: , 1:14].max(axis=1)
reason_2 = reason_for_absence.loc[: , 15:17].max(axis=1)
reason_3 = reason_for_absence.loc[: , 18:21].max(axis=1)
reason_4 = reason_for_absence.loc[: , 22:].max(axis=1)

### Concat the reason values

In [22]:
df = pd.concat([df, reason_1, reason_2, reason_3, reason_4], axis=1)

In [23]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

In [24]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [25]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [26]:
df.columns = column_names

In [27]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

### Reordering the Columns

In [28]:
column_names_reorder = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [29]:
df = df[column_names_reorder]

In [30]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [31]:
df_reason_mod = df.copy()

In [32]:
df_reason_mod.head(7)

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   
5         0         0         0         1  10/07/2015                     179   
6         0         0         0         1  17/07/2015                     361   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8

### Analysis of Date columns 

In [33]:
type(df_reason_mod['Date'][0])

str

In [34]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format='%d/%m/%Y')

In [35]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

### Extracting month and storing it in seperate column 

In [36]:
df_reason_mod['Date'][0].month

7

In [37]:
month_list = []
for i in range(len(df_reason_mod)):
    month_list.append(df_reason_mod['Date'][i].month)

print(month_list)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1

In [38]:
df_reason_mod['Month'] = month_list

In [39]:
df_reason_mod.head(20)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0          0         0         0         1 2015-07-07                     289   
1          0         0         0         0 2015-07-14                     118   
2          0         0         0         1 2015-07-15                     179   
3          1         0         0         0 2015-07-16                     279   
4          0         0         0         1 2015-07-23                     289   
5          0         0         0         1 2015-07-10                     179   
6          0         0         0         1 2015-07-17                     361   
7          0         0         0         1 2015-07-24                     260   
8          0         0         1         0 2015-07-06                     155   
9          0         0         0         1 2015-07-13                     235   
10         1         0         0         0 2015-07-20                     260   
11         1         0         0         0 2015-07-14                     260   
12         1         0         0         0 2015-07-15                     260   
13         1         0         0         0 2015-07-15                     179   
14         0         0         0         1 2015-07-15                     179   
15         1         0         0         0 2015-07-17                     246   
16         0         0         0         1 2015-07-17                     179   
17         0         0         1         0 2015-07-27                     179   
18         1         0         0         0 2015-07-30                     189   
19         0         0         0         1 2015-08-05                     248   

    Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                 36   33                  239.554               30   
1                 13   50                  239.554               31   
2                 51   38                  239.554               31   
3                  5   39                  239.554               24   
4                 36   33                  239.554               30   
5                 51   38                  239.554               31   
6                 52   28                  239.554               27   
7                 50   36                  239.554               23   
8                 12   34                  239.554               25   
9                 11   37                  239.554               29   
10                50   36                  239.554               23   
11                50   36                  239.554               23   
12                50   36                  239.554               23   
13                51   38                  239.554               31   
14                51   38                  239.554               31   
15                25   41                  239.554               23   
16                51   38                  239.554               31   
17                51   38                  239.554               31   
18                29   33                  239.554               25   
19                25   47                  205.917               32   

    Education  Children  Pets  Absenteeism Time in Hours  Month  
0           1         2     1                          4      7  
1           1         1     0                          0      7  
2           1         0     0                          2      7  
3           1         2     0                          4      7  
4           1         2     1                          2      7  
5           1         0     0                          2      7  
6           1         1     4                          8      7  
7           1         4     0                          4      7  
8           1         2     0                         40      7  
9           3         1     1                          8      7  
10          1         4     0                          8      7  
11          1     

### Extract Day of the Week 

In [40]:
df_reason_mod['Date'][1].weekday()

1

In [41]:
def week_to_day(date_value):
    return date_value.weekday()

In [42]:
df_reason_mod['Day of the week'] = df_reason_mod['Date'].apply(week_to_day)

In [43]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month  Day of the week  
0         2     1                          4      7                1  
1         1     0                          0      7                1  
2         0     0                          2      7                2  
3         2     0                          4      7                3  
4         2     1                          2      7                3

In [44]:
df_reason_mod.drop(['Date'], axis=1, inplace=True)

In [45]:
df_reason_mod.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours', 'Month', 'Day of the week'],
      dtype='object')

In [46]:
df_reason_mod = df_reason_mod[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
                               'Day of the week' , 'Month',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']]

In [47]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [48]:
df_reason_date_mod = df_reason_mod.copy()

In [49]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [50]:
type(df_reason_date_mod['Transportation Expense'][0])

numpy.int64

In [51]:
type(df_reason_date_mod['Distance to Work'][0])

numpy.int64

In [52]:
type(df_reason_date_mod['Age'][0])

numpy.int64

In [53]:
type(df_reason_date_mod['Daily Work Load Average'][0])

numpy.float64

In [54]:
type(df_reason_date_mod['Body Mass Index'][0])

numpy.int64

In [55]:
df_reason_date_mod['Education'].unique()

array([1, 3, 2, 4])

In [56]:
df_reason_date_mod['Education'].value_counts()

Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

In [57]:
df_reason_date_mod['Education'] = df_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [58]:
df_reason_date_mod['Education'].unique()

array([0, 1])

In [59]:
df_reason_date_mod['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

In [60]:
df_reason_date_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [61]:
df_preprocessed = df_reason_date_mod.copy()

In [62]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Creating Logistic Regression for Absenteeism Problem 

### Importing the Libraries 

In [63]:
import pandas as pd 
import numpy as np 

### Check or load the data 

In [64]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Creating the Target 

In [65]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [66]:
targets = np.where(df_preprocessed['Absenteeism Time in Hours']>df_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [67]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [68]:
df_preprocessed['Excessive Absenteesim'] = targets

In [69]:
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the week  Month  \
0         0         0         0         1                1      7   
1         0         0         0         0                1      7   
2         0         0         0         1                2      7   
3         1         0         0         0                3      7   
4         0         0         0         1                3      7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteesim  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Comments on the Target 

In [70]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [71]:
data_with_targets = df_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the week', 'Daily Work Load Average', 'Distance to Work'], axis=1)
data_with_targets is df_preprocessed

False

In [72]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month  Transportation Expense  Age  \
0         0         0         0         1      7                     289   33   
1         0         0         0         0      7                     118   50   
2         0         0         0         1      7                     179   38   
3         1         0         0         0      7                     279   39   
4         0         0         0         1      7                     289   33   

   Body Mass Index  Education  Children  Pets  Excessive Absenteesim  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

### Selecting the input/features for our Algorithms

In [73]:
data_with_targets.shape

(700, 12)

In [74]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

### Standardize the input/features 

In [75]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [76]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns], axis=1)
        self.var_ = np.var(X[self.columns], axis=1)
        return self 

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [77]:
unscaled_inputs.columns

Index(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'],
      dtype='object')

In [78]:
# columns_to_scale = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Day of the week',
#        'Month', 'Transportation Expense', 'Distance to Work', 'Age',
#        'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
#        'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [79]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [80]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [81]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [82]:
scaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4     Month  Transportation Expense  \
0         0         0         0         1  0.182726                1.005844   
1         0         0         0         0  0.182726               -1.574681   
2         0         0         0         1  0.182726               -0.654143   
3         1         0         0         0  0.182726                0.854936   
4         0         0         0         1  0.182726                1.005844   

        Age  Body Mass Index  Education  Children      Pets  
0 -0.536062         0.767431          0  0.880469  0.268487  
1  2.130803         1.002633          0 -0.019280 -0.589690  
2  0.248310         1.002633          0 -0.919030 -0.589690  
3  0.405184        -0.643782          0  0.880469 -0.589690  
4 -0.536062         0.767431          0  0.880469  0.268487

In [83]:
scaled_inputs.shape

(700, 11)

### Splitting the data into train and test and shuffle it

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, test_size=0.2, random_state=20)

In [86]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((560, 11), (560,), (140, 11), (140,))

### Logistics Regression with sklearn

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [88]:
reg = LogisticRegression()

In [89]:
reg.fit(x_train, y_train)

LogisticRegression()

In [90]:
reg.score(x_train, y_train)

0.7732142857142857

### Manual check the accuracy

In [91]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [92]:
np.sum(model_output == y_train) / model_output.shape[0]

0.7732142857142857

### Finding the intercept and coefficient 

In [93]:
reg.intercept_

array([-1.6469898])

In [94]:
reg.coef_

array([[ 2.80000644,  0.95174778,  3.1140605 ,  0.83835931,  0.15897713,
         0.60513709, -0.16990589,  0.27998236, -0.21017416,  0.34842434,
        -0.27721907]])

In [95]:
feature_name = unscaled_inputs.columns.values

In [96]:
summary_table = pd.DataFrame(columns=['Feature Name'], data=feature_name)
# summary_table['Co-efficients'] = reg.coef_.T
summary_table['Co-efficients'] = np.transpose(reg.coef_)
summary_table

Feature Name  Co-efficients
0                 Reason_1       2.800006
1                 Reason_2       0.951748
2                 Reason_3       3.114061
3                 Reason_4       0.838359
4                    Month       0.158977
5   Transportation Expense       0.605137
6                      Age      -0.169906
7          Body Mass Index       0.279982
8                Education      -0.210174
9                 Children       0.348424
10                    Pets      -0.277219

In [97]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Co-efficients
0                Intercept      -1.646990
1                 Reason_1       2.800006
2                 Reason_2       0.951748
3                 Reason_3       3.114061
4                 Reason_4       0.838359
5                    Month       0.158977
6   Transportation Expense       0.605137
7                      Age      -0.169906
8          Body Mass Index       0.279982
9                Education      -0.210174
10                Children       0.348424
11                    Pets      -0.277219

In [98]:
summary_table['Odds_ratio'] = np.exp(summary_table['Co-efficients'])
summary_table

Feature Name  Co-efficients  Odds_ratio
0                Intercept      -1.646990    0.192629
1                 Reason_1       2.800006   16.444753
2                 Reason_2       0.951748    2.590233
3                 Reason_3       3.114061   22.512270
4                 Reason_4       0.838359    2.312570
5                    Month       0.158977    1.172311
6   Transportation Expense       0.605137    1.831503
7                      Age      -0.169906    0.843744
8          Body Mass Index       0.279982    1.323106
9                Education      -0.210174    0.810443
10                Children       0.348424    1.416833
11                    Pets      -0.277219    0.757888

In [99]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature Name  Co-efficients  Odds_ratio
3                 Reason_3       3.114061   22.512270
1                 Reason_1       2.800006   16.444753
2                 Reason_2       0.951748    2.590233
4                 Reason_4       0.838359    2.312570
6   Transportation Expense       0.605137    1.831503
10                Children       0.348424    1.416833
8          Body Mass Index       0.279982    1.323106
5                    Month       0.158977    1.172311
7                      Age      -0.169906    0.843744
9                Education      -0.210174    0.810443
11                    Pets      -0.277219    0.757888
0                Intercept      -1.646990    0.192629

### Testing the model

In [103]:
reg.score(x_test, y_test)

0.75

In [104]:
from sklearn.model_selection import cross_val_score

cross_val_score(reg, scaled_inputs, targets, cv=10)

array([0.77142857, 0.84285714, 0.8       , 0.72857143, 0.82857143,
       0.8       , 0.62857143, 0.55714286, 0.82857143, 0.75714286])

In [106]:
predicted_proba = reg.predict_proba(x_test)

In [107]:
predicted_proba

array([[0.71342516, 0.28657484],
       [0.5873216 , 0.4126784 ],
       [0.44016153, 0.55983847],
       [0.78163061, 0.21836939],
       [0.08407928, 0.91592072],
       [0.3348226 , 0.6651774 ],
       [0.29971206, 0.70028794],
       [0.13112385, 0.86887615],
       [0.78627908, 0.21372092],
       [0.74906578, 0.25093422],
       [0.49395555, 0.50604445],
       [0.22492002, 0.77507998],
       [0.07135527, 0.92864473],
       [0.73173354, 0.26826646],
       [0.30957854, 0.69042146],
       [0.54726422, 0.45273578],
       [0.55051921, 0.44948079],
       [0.53926379, 0.46073621],
       [0.40197149, 0.59802851],
       [0.05365482, 0.94634518],
       [0.70030387, 0.29969613],
       [0.78163061, 0.21836939],
       [0.42028246, 0.57971754],
       [0.42028246, 0.57971754],
       [0.24801464, 0.75198536],
       [0.74567806, 0.25432194],
       [0.51026557, 0.48973443],
       [0.8569309 , 0.1430691 ],
       [0.20365204, 0.79634796],
       [0.78163061, 0.21836939],
       [0.

In [108]:
predicted_proba.shape

(140, 2)

### Saving the model 

In [109]:
import pickle

with open('Model/Logistic_Regression_model.pkl', 'wb') as file:
    pickle.dump(reg, file)

In [110]:
with open('Model/scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file) 

### Deploying the model 