# Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
type(my_list)

list

In [3]:
myarr = np.array(my_list)
type(myarr)

numpy.ndarray

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(shape=(3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(shape=(4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(3, 4)

array([[0.14026987, 0.29575784, 0.24939324, 0.0448194 ],
       [0.09528913, 0.58526398, 0.77029803, 0.70408518],
       [0.24383487, 0.59231664, 0.22788998, 0.53738529]])

In [14]:
np.random.randn(3, 4)

array([[-1.24955757, -0.01221885,  1.53783637,  0.14242932],
       [-1.46769056, -1.23590872,  1.0666317 , -3.36132667],
       [-0.4565617 ,  0.20911671,  0.67770422,  0.10493426]])

In [15]:
np.random.randint(0, 201, size=(5, 5))

array([[ 46,  36, 110,  31, 159],
       [169, 142, 123,  17, 115],
       [185,  75,  64, 116, 200],
       [ 98, 132, 175,  60, 107],
       [ 12,  91,  89, 135,  76]])

In [16]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [17]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
randarr = np.random.randint(0, 20, 10)

In [20]:
randarr

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [21]:
randarr.max()

18

In [22]:
randarr.min()

1

In [23]:
randarr.argmax()

1

In [24]:
randarr.argmin()

7

In [25]:
randarr.dtype

dtype('int64')

In [26]:
arr.shape

(25,)

In [27]:
arr = arr.reshape(5, 5)

In [28]:
arr.shape

(5, 5)

In [30]:
randarr

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [31]:
randarr[1:5]

array([18, 10, 10,  3])

In [32]:
randarr[:5]

array([ 6, 18, 10, 10,  3])

In [33]:
randarr[5:]

array([ 7,  2,  1, 11,  5])

In [35]:
randarr[5:] = 100
randarr

array([  6,  18,  10,  10,   3, 100, 100, 100, 100, 100])

In [57]:
randarr = np.random.randint(0, 5, 10)
randarr

array([0, 2, 4, 2, 0, 4, 1, 2, 0, 1])

In [58]:
slice_of_arr  = randarr[:5]
slice_of_arr

array([0, 2, 4, 2, 0])

In [59]:
slice_of_arr[:] = 99

In [60]:
randarr

array([99, 99, 99, 99, 99,  4,  1,  2,  0,  1])

In [61]:
arr_2d = np.random.randint(0, 99, size=(3,3))
arr_2d

array([[41, 76, 50],
       [62, 95, 51],
       [95,  3, 93]])

In [62]:
randarr>10

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [63]:
randarr + 5

array([104, 104, 104, 104, 104,   9,   6,   7,   5,   6])

In [64]:
randarr - 2

array([97, 97, 97, 97, 97,  2, -1,  0, -2, -1])

In [65]:
randarr * 4

array([396, 396, 396, 396, 396,  16,   4,   8,   0,   4])

In [66]:
randarr/2

array([49.5, 49.5, 49.5, 49.5, 49.5,  2. ,  0.5,  1. ,  0. ,  0.5])

In [67]:
randarr//2

array([49, 49, 49, 49, 49,  2,  0,  1,  0,  0])

In [68]:
randarr + randarr

array([198, 198, 198, 198, 198,   8,   2,   4,   0,   2])

In [69]:
randarr - randarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
randarr/ randarr

/tmp/ipykernel_6957/3980430846.py:1: RuntimeWarning: invalid value encountered in divide
  randarr/ randarr


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., nan,  1.])

In [71]:
np.sqrt(randarr)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       2.        , 1.        , 1.41421356, 0.        , 1.        ])

In [72]:
np.square(randarr)

array([9801, 9801, 9801, 9801, 9801,   16,    1,    4,    0,    1])

In [73]:
np.sin(randarr)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.7568025 ,  0.84147098,  0.90929743,  0.        ,  0.84147098])

In [74]:
np.cos(randarr)

array([ 0.03982088,  0.03982088,  0.03982088,  0.03982088,  0.03982088,
       -0.65364362,  0.54030231, -0.41614684,  1.        ,  0.54030231])

In [75]:
np.log(randarr)

/tmp/ipykernel_6957/2641870028.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(randarr)


array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       1.38629436, 0.        , 0.69314718,       -inf, 0.        ])

In [77]:
randarr.sum()

503

In [79]:
randarr.std(), randarr.var()

(48.709444669386244, 2372.6099999999997)

In [80]:
arr_2d

array([[41, 76, 50],
       [62, 95, 51],
       [95,  3, 93]])

In [83]:
arr_2d.sum(axis=0), arr_2d.sum(axis=1)

(array([198, 174, 194]), array([167, 208, 191]))