# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [72]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [73]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3], 
               [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [74]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [75]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [76]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 18, numpy.ndarray)

In [77]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(a2)
data

0  1  2
0  1  2  3
1  4  5  6

In [78]:
# Create an array of shape (10, 2) with only ones
a4 = np.ones((10,2))
a4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
# Create an array of shape (7, 2, 3) of only zeros
a5 = np.zeros((7,2,3))
a5

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [80]:
# Create an array within a range of 0 and 100 with step 3
a6 = np.arange(0, 100, 3)
a6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [81]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randint_array = np.random.randint(0,10,size=(7,2))
randint_array

array([[3, 8],
       [2, 6],
       [5, 7],
       [8, 4],
       [0, 2],
       [9, 7],
       [5, 7]])

In [82]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array = np.random.random((3, 5))
random_array

array([[0.70301896, 0.3636296 , 0.97178208, 0.96244729, 0.2517823 ],
       [0.49724851, 0.30087831, 0.28484049, 0.03688695, 0.60956433],
       [0.50267902, 0.05147875, 0.27864646, 0.90826589, 0.23956189]])

In [83]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_int = np.random.randint(0, 10, size=(4,6))
rand_int

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [84]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randon_int = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(randon_int)

array([1, 2, 3, 4, 5, 7, 9])

In [85]:
# Find the 0'th index of the latest array you created
randon_int[0]

array([9, 1, 3, 7, 4, 9, 3])

In [86]:
# Get the first 2 rows of latest array you created
randon_int[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [87]:
# Get the first 2 values of the first 2 rows of the latest array
randon_int[0:2, 0:2]

array([[9, 1],
       [5, 3]])

In [88]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
first_array = np.random.randint(0, 10, size=(3, 5))
ones_array = np.ones((3, 5))

In [89]:
# Add the two arrays together
first_array+ones_array

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [90]:
# Create another array of ones of shape (5, 3)
second_ones = np.ones((5,3))

In [91]:
# Try add the array of ones and the other most recent array together
first_array+second_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [92]:
# Create another array of ones of shape (3, 5)
third_ones = np.ones((3,5))

In [93]:
# Subtract the new array of ones from the other most recent array
first_array-third_ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [94]:
# Multiply the ones array with the latest array
first_array*third_ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [95]:
# Take the latest array to the power of 2 using '**'
first_array**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [96]:
# Do the same thing with np.square()
np.square(first_array)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [97]:
# Find the mean of the latest array using np.mean()
np.mean(first_array)

3.8666666666666667

In [98]:
# Find the maximum of the latest array using np.max()
np.max(first_array)

9

In [99]:
# Find the minimum of the latest array using np.min()
np.min(first_array)

0

In [100]:
# Find the standard deviation of the latest array
first_array.std()

2.578543947441829

In [101]:
# Find the variance of the latest array
first_array.var()

6.648888888888889

In [102]:
# Reshape the latest array to (3, 5, 1)
first_array.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [103]:
# Transpose the latest array
first_array.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [104]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
dot1 = np.random.randint(0, 10, size=(3,3))
dot1
dot2 = np.random.randint(0,10,size=(3,2))
dot2

array([[1, 4],
       [7, 9],
       [8, 8]])

In [105]:
# Perform a dot product on the two newest arrays you created
np.dot(dot1, dot2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [106]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
dot3 = np.random.randint(0, 10, size=(4,3))
dot4 = np.random.randint(0, 10, size=(4,3))

In [107]:
# Perform a dot product on the two newest arrays you created
np.dot(dot3, dot4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [108]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(dot3, dot4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [109]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a11 = np.random.randint(0, 10, size=(3,4))
a12 = np.random.randint(0, 10, size=(3,4))

In [110]:
# Compare the two arrays with '>'
a11>a12

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

What happens when you compare the arrays with `>`?

In [111]:
# Compare the two arrays with '>='
a11>=a12

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [112]:
# Find which elements of the first array are greater than 7
a11>7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [113]:
# Which parts of each array are equal? (try using '==')
a11 == a12

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [114]:
# Sort one of the arrays you just created in ascending order
np.sort(a11)

array([[4, 6, 6, 7],
       [2, 2, 5, 7],
       [0, 2, 2, 4]])

In [115]:
# Sort the indexes of one of the arrays you just created
np.argsort(a11)

array([[3, 0, 1, 2],
       [0, 3, 2, 1],
       [0, 1, 3, 2]])

In [116]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a11)

2

In [117]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a11)

8

In [118]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a11, axis=1)

array([2, 1, 2])

In [119]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a12, axis=0)

array([0, 0, 2, 2])

In [120]:
# Create an array of normally distributed random numbers
nor_arr = np.random.randn(3, 5)
nor_arr

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [122]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0,100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.