In [1]:
import numpy as np

# Datatype & Attributes

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.4],
              [4, 5.4, 6.7]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2

array([[1. , 2. , 3.4],
       [4. , 5.4, 6.7]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
import pandas as pd
df = pd.DataFrame(a2)

df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.4  6.7

## Creating a Numpy arry

In [15]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [16]:
ones_array = np.ones((2, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones_array.dtype

dtype('float64')

In [18]:
type(ones_array)

numpy.ndarray

In [19]:
zeros_array = np.zeros((2, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 4, 1, 5, 4],
       [1, 0, 7, 8, 2],
       [0, 1, 4, 1, 6]])

In [22]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.9610813 , 0.52667985, 0.19163012],
       [0.4411336 , 0.60428367, 0.24907456],
       [0.25313858, 0.54321453, 0.14897276],
       [0.01608493, 0.37805452, 0.00763336],
       [0.3583086 , 0.44015746, 0.45055928]])

In [23]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.58108221, 0.20075262, 0.71493195],
       [0.60736046, 0.02085427, 0.72192332],
       [0.12725662, 0.44938491, 0.71466995],
       [0.03080537, 0.62574207, 0.42659252],
       [0.76177252, 0.26310251, 0.76318427]])

In [24]:
# Pseudo-random numbers
np.random.seed(2)

random_array_4 = np.random.randint(1, 10, size=(5,3))
random_array_4

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6],
       [5, 5, 6],
       [8, 4, 7]])

## Viewing Array and Matrices

In [25]:
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
random_array_4

array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6],
       [5, 5, 6],
       [8, 4, 7]])

In [27]:
a4 = np.random.randint(1, 11, size=(2,3,4,5))
a4

array([[[[ 5,  4,  8,  7,  2],
         [ 4,  6,  9,  5,  7],
         [ 4, 10,  3,  1,  5],
         [ 3,  5,  2,  8,  9]],

        [[ 3, 10,  9,  8,  2],
         [ 7,  9,  6, 10, 10],
         [10,  4,  1,  1,  3],
         [ 9,  9,  3, 10,  7]],

        [[ 6,  7,  7,  7,  4],
         [ 9,  3,  2,  5,  9],
         [ 2,  7, 10,  6,  2],
         [ 3,  5,  8,  7,  5]]],


       [[[ 6,  9,  4,  1,  1],
         [ 6,  8,  6,  1,  9],
         [ 7,  6,  2,  8,  5],
         [ 4,  7,  2,  5,  1]],

        [[ 9,  6,  5,  3, 10],
         [ 8,  2, 10,  3,  2],
         [ 1,  8,  2,  9, 10],
         [ 1,  8,  1,  6,  3]],

        [[ 6,  2,  4,  4,  2],
         [ 9,  7,  9,  2,  6],
         [ 8,  1, 10,  2,  6],
         [10,  3,  1,  1,  5]]]])

## Manipulating and comparing arrays

### Arithmetic

In [28]:
a1 + a2

array([[2. , 4. , 6.4],
       [5. , 7.4, 9.7]])

In [29]:
a1 - a2

array([[ 0. ,  0. , -0.4],
       [-3. , -3.4, -3.7]])

In [30]:
a1 * a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 10.8, 20.1]])

In [31]:
a1 / a2

array([[1.        , 1.        , 0.88235294],
       [0.25      , 0.37037037, 0.44776119]])

In [32]:
a2, a3

(array([[1. , 2. , 3.4],
        [4. , 5.4, 6.7]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [33]:
a2.reshape(2,3,-1) *a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.8,  27.2,  30.6]],

       [[ 40. ,  44. ,  48. ],
        [ 70.2,  75.6,  81. ],
        [107.2, 113.9, 120.6]]])

In [34]:
a2 ** 2

array([[ 1.  ,  4.  , 11.56],
       [16.  , 29.16, 44.89]])

In [35]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggrigation

In [40]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.41483569, 0.18282216, 0.17784996, 0.60858004, 0.32895309,
       0.82156507, 0.09197091, 0.49292009, 0.90432271, 0.50598456])

In [41]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

6.27 ms ± 77.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
29.3 µs ± 329 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [42]:
np.mean(a2)

3.75

In [43]:
np.max(a2)

6.7

In [44]:
np.min(a2)

1.0

In [45]:
np.std(a2)

1.9250541117935709

In [1]:
np.var(a1)

NameError: name 'np' is not defined